static_host_map:
  "Внутренний IPV6 сети nebula": ["внешний IPV4 VPS:4242"]
  #"192.168.100.1"
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/lighthouse.crt
  key: /etc/nebula/lighthouse.key

static_ips:
  # Публичный адрес, по которому маяк доступен извне
  - внешний IPV4 VPS

lighthouse:
  am_lighthouse: true
  # Маяк не нуждается в списке других маяков
  hosts: []

listen:
  # Слушаем на IPv4 и IPv6 для входящих подключений от клиентов
  host: "[::]"
  port: 4242

punchy:
  punch: true
  respond: true

# Настройка виртуального интерфейса
tun:
  dev: nebula1
  drop_local_broadcast: true
  drop_multicast: true
  tx_queue: 500
  mtu: 1280

# Если NAT у клиентов будет слишком жестким (Symmetric NAT), маяк поможет как ретранслятор
relay:
  am_relay: true    # Разрешаем другим использовать этот маяк как ретранслятор
  use_relays: false # Маяку не нужно искать другие релеи
  relays: []        # Удаляем собственный IP отсюда


firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    # Разрешаем ICMP (пинг) внутри сети
    - port: any
      proto: icmp
      host: any
    # Разрешаем весь трафик между вашими узлами по IPv6/IPv4
    - port: any
      proto: any
      host: any
